name = "Keldysh"
uuid = "50f2bc7e-5fd7-11e9-13c7-85fb88b4f34f"
authors = ["Joseph Kleinhenz <kleinhenz.joseph@gmail.com>"]
version = "0.5.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
